### ISSUE TITLE
Segmentation fault in Transform.hpp

### ISSUE THREAD

**Issue by itsdsk** [gadomski/cpd#114]
I'm trying to work this cpd implementation into a c++ project on Ubuntu 16.04 (eOS) and qtcreator 4.1.0.

At this point I get a segmentation fault:

`    cpd::AffineResult result = affine.run(fixed, moving);
`
This is output several times just before the crash:

`RTTI symbol not found for class 'cpd::Affine'
`

I don't particuarly understand debugging information, but it points to line 132 of Transform.hpp as the point where the fault occurs:

`        Normalization normalization(fixed, moving, linked());
`
Thanks!

**Comment by gadomski** [comment]
That `linked()` argument is a relatively new addition, so my first guess is that you've got two different versions of CPD on your system somehow. Blow away everything CPD related, reinstall, and see if the problem is still there.

Because I do this often, I usually install home-built software to `$HOME/local` (instead of `/usr/local`) so I can easily just `rm -rf $HOME/local` and ensure that I've cleaned up everything.

**Comment by itsdsk** [comment]
Thanks for the quick reply :D You were right - there were some old versions which after deleting them, stopped the error above.

I'm still getting a segmentation fault on Transform.hpp however, now at line 156:

`                
Probabilities probabilities = m_gauss_transform->compute(
    fixed, result.points, result.sigma2, m_outliers);
`

(2nd line is 156)

**Comment by gadomski** [comment]
Any way you can provide your data to me so I can debug locally?

**Comment by itsdsk** [comment]
I could send you the whole project but openFrameworks needs to be installed to run it (it's a big library and there are quite a few steps to get it set up).

Otherwise here's my code to run cpd:

` 
     cpd::Matrix fixed;     // (both ~6000x2)
     cpd::Matrix moving; // values meant to range from -1. to 1.

    cpd::Affine affine;
    affine.max_iterations(1).correspondence(true);
    cpd::AffineResult result = affine.run(fixed, moving);
`
Here's what I'm seeing:
http://storage8.static.itmages.com/i/17/0413/h_1492095120_4347653_41c1293aab.png

I did just notice that, although my cpd::Matrix is meant to have values from -1 to 1, at the point of the segmentation fault some values exceed that range.

The problem might be with my matrix creation?

**Comment by gadomski** [comment]
In your debugger, can you confirm that `m_gauss_transform` is valid? That's the likeliest (imo) place you could be getting a segfault right there.

I don't really need the whole project, just the points themselves will do to go on with. Can you do a text file export of those points?

**Comment by itsdsk** [comment]
m_gauss_transform looks valid:

`m_gauss_transform
@0x47e9a30
std::unique_ptr<cpd::GaussTransform, std::default_delete<cpd::GaussTransform>>

data
@0x47e9a30
cpd::GaussTransform`


cpd::Matrix moving is here: https://pastebin.com/sb5bJHgQ

I'm also doing `.run(moving, moving);` just to test it right now, as it's 1:1 and my fixed matrix is ~100k, don't think that's the problem though

**Comment by gadomski** [comment]
Is `.run(moving, moving)` also segfaulting?

**Comment by itsdsk** [comment]
Yeah it is

**Comment by gadomski** [comment]
Using the `cpd-rigid` example, I was able to successfully retrieve a "identity" transformation by comparing the moving points to themselves:

```
$ examples/build/cpd-rigid ~/Desktop/moving.txt ~/Desktop/moving.txt
{
	"iterations" : 55,
	"rotation" :
	[
		[
			0.99999999999999933,
			-1.6653345369377348e-16
		],
		[
			-1.1102230246251565e-16,
			0.99999999999999978
		]
	],
	"runtime" : 55.387165000000003,
	"scale" : 0.99999999999996936,
	"sigma2" : 3.0627200791767849e-14,
	"translation" :
	[
		[
			1.4060618879180429e-15
		],
		[
			8.2919782151691379e-16
		]
	]
}
```

So now we turn to your code to try to find the problem. Any way you can provide some/all of the code you're running so I can take a look? I'm not yet willing to *just* blame it on your code, you could be using my API properly and the bug could be inside cpd.

**Comment by itsdsk** [comment]
The debugger points to an internal Eigen function (looks like assembly) after doing a clean + rebuild. I have a feeling that my problem is much higher up though - it's almost certainly a dodgy implementation rather than a problem with your cpd library!

I want to run the same test as you just did, but when I try to build the examples I get this error from cmake:

```
CMake Error at CMakeLists.txt:4 (find_package):
  By not providing "FindCpd.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "Cpd", but
  CMake did not find one.

  Could not find a package configuration file provided by "Cpd" with any of
  the following names:

    CpdConfig.cmake
    cpd-config.cmake

  Add the installation prefix of "Cpd" to CMAKE_PREFIX_PATH or set "Cpd_DIR"
  to a directory containing one of the above files.  If "Cpd" provides a
  separate development package or SDK, be sure it has been installed.

```

**Comment by gadomski** [comment]
Depending on where you installed cpd, you might have to set `Cpd_DIR` when building the examples, e.g. `cmake .. -DCpd_DIR=/usr/local/lib/cmake/cpd` or some such.

Hm, if the segfault is happening in Eigen, one of your matrices might not be set up correctly. Just shooting in the dark here though.

**Comment by itsdsk** [comment]
I passed the cpd/build/tests/ successfully so I think that's confirmation that the problem isn't in cpd.

My project is so messy that I'm embarrassed to put it on github in it's current state, so I'll go back to the drawing board for now. Thanks for the help and understanding anyhow :+1:

**Comment by gadomski** [comment]
Okay, no problem! Feel free to reopen if this issue persists.
