### ISSUE TITLE
data sets format used in CPD.

### ISSUE THREAD

**Issue by lujaindong** [gadomski/cpd#122]
I noticed there  are all data sets in .csv format under the directory fixtures. 
Can other file format be used in CPD, like vtu,vtk ,obj?
I have data sets with the format above and I dont know how to convert them. Any idea?
Thanks advance.

**Comment by x1597275** [comment]
how do you solve it?

**Comment by x1597275** [comment]
> I noticed there are all data sets in .csv format under the directory fixtures.
> Can other file format be used in CPD, like vtu,vtk ,obj?
> I have data sets with the format above and I dont know how to convert them. Any idea?
> Thanks advance.

would you tell me 
how do you solve it?

**Comment by x1597275** [comment]
> I noticed there are all data sets in .csv format under the directory fixtures.
> Can other file format be used in CPD, like vtu,vtk ,obj?
> I have data sets with the format above and I dont know how to convert them. Any idea?
> Thanks advance.

could you tell me how do you solve it ?
