### ISSUE TITLE
obtain the vector field using the nonrigid transformation

### ISSUE THREAD

**Issue by lujaindong** [gadomski/cpd#123]
Hi I am using the nonrigid transformation to align my own data sets. The code works fine but I can't find  any output results about the registration. How can I get the vector field using this CPD? Any idea?

**Comment by gadomski** [comment]
You can get the vector field by subtracting the pre-registration points from the post-registration points:

```cpp
cpd::Matrix fixed = load_points_from_somewhere();
cpd::Matrix moving = load_points_from_somewhere();
cpd::NonrigidResult result = cpd::nonrigid(fixed, moving);
cpd::Matrix vector_field = result.points - moving;
```
