### ISSUE TITLE
can I use cpd to deal one set points(2000) and one set points(70)?

### ISSUE THREAD

**Issue by wanghai1988** [gadomski/cpd#125]

**Comment by gadomski** [comment]
If you're asking "can one set of points have 2000 points and the other have 70?" the answer is yes it will work, but it may or may not give you a correct result — you'll have to give it a try and find out.

If not, please re-open this issue and clarify. Thanks!

**Comment by wanghai1988** [comment]
yes you are right ! but ,,Is there any other method can solve this situation?

**Comment by gadomski** [comment]
I don't understand the problem, can you explain further? Thanks.

**Comment by RolandZhu** [comment]
Hi, may I ask for some advice about what lambda and beta value are when you registered 70 points to 2000? I'm doing the similar thing right now but didn't get a good result. Thanks.

**Comment by gadomski** [comment]
> yes it will work, but it may or may not give you a correct result

I haven't tried 70 to 2000 personally, and as I said above it may not give you a correct result. I generally try to have similar numbers of points in each point set.

Sorry I can't be more help.
