### ISSUE TITLE
Registration won't work - malloc error

### ISSUE THREAD

**Issue by P-Kinsella** [gadomski/cpd#128]
When I try to run the examples I get the following error:

Basic(73892,0x1029af3c0) malloc: *** error for object 0x103961220: pointer being freed was not allocated

I cannot seem to find why this is happening and have tried the rigid.cpp, random.cpp and fgt.cpp examples but get the same result. Any help you can give is appreciated,

**Comment by P-Kinsella** [comment]
I should clarify, that I'm running the code on a mac with xcode 8.1

**Comment by gadomski** [comment]
Hm, I can't replicate the issue. Does the test suite pass?
