### ISSUE TITLE
CMake error 

### ISSUE THREAD

**Issue by ahmedmaalej** [gadomski/cpd#129]
I build fgt following your instructions:
BUILD_SHARED_LIBS=OFF,
gtest_force_shared_crt=ON. 
To avoid  MSVC config mucking.
I get fgt.lib in Debug and Release modes when I build the fgt.sln (using ALL_BUILD as the starting project).
But when I try to build CPD, I keep getting this error when using CMake to compile CPD, even with disabling WITH_FGT option:

 CMake Error at D:/CPD_cpp/fgt_build/fgt-config.cmake:1 (include):
  include could not find load file:
    D:/CPD_cpp/fgt_build/fgt-targets.cmake
Call Stack (most recent call first):
  CMakeLists.txt:27 (find_package)

CMake Error at D:/CPD_cpp/fgt_build/fgt-config.cmake:1 (include):
  include could not find load file:
    D:/CPD_cpp/fgt_build/fgt-targets.cmake
Call Stack (most recent call first):
  CMakeLists.txt:30 (find_package)

Any suggestions ?

**Comment by ahmedmaalej** [comment]
It seems the error has gone when copying th fgt_build file in the fgt_source file (initially seperated).
Enabeling the WITH_FGT option gives 👍 
CMake Error at CMakeLists.txt:30 (find_package):
  By not providing "FindFgt.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "Fgt", but
  CMake did not find one.

  Could not find a package configuration file provided by "Fgt" with any of
  the following names:

    FgtConfig.cmake
    fgt-config.cmake

  Add the installation prefix of "Fgt" to CMAKE_PREFIX_PATH or set "Fgt_DIR"
  to a directory containing one of the above files.  If "Fgt" provides a
  separate development package or SDK, be sure it has been installed.

**Comment by gadomski** [comment]
Did you `INSTALL` FGT? The `fgt-targets.cmake` file might only be created/placed correctly during an install.
