### ISSUE TITLE
Why 0.5.1 release tarball changed?

### ISSUE THREAD

**Issue by andypost** [gadomski/cpd#136]
In Alpinelinux 0.5.1 was packaged year ago but some time ago builder reported that chacksum changed
I filed updated of checksum https://github.com/alpinelinux/aports/pull/4982

But can someone clarify why that could happen?
Is tarbal was repackaged for the release?

**Comment by gadomski** [comment]
No idea, sorry. I haven't mucked with the tarballs (e.g. https://github.com/gadomski/cpd/archive/v0.5.1.tar.gz) and haven't force-pushed any tags.
