### ISSUE TITLE
Build error: External symbols that cannot be resolved “std::unique_ptr<GaussTransform>::make_default(void)"

### ISSUE THREAD

**Issue by Micalson** [gadomski/cpd#139]
Hi, thank you for your code about cpd. I got the error while compiling the code. The error is : 
   External symbols that cannot be resolved “std::unique_ptr<GaussTransform>::make_default(void)"
The development environment is visual studio 2013, eigen3. Could you tell me the reason about this error?
Thank you for your reply. @gadomski 

best regards

**Comment by gadomski** [comment]
I'm running Visual Studio 2017, Eigen 3.3.7, and can't reproduce your issue. I'd recommend updating your Visual Studio and trying again. If you can reproduce the issue with the latest Visual Studio, please re-open this issue.
