### ISSUE TITLE
build error C2220 on windows with VS2015

### ISSUE THREAD

**Issue by HyeonjunKimLay** [gadomski/cpd#140]
Hi. I've used cpd lib very well for a few months. 
Now i am trying to build cpd another computer, but It's failed.
My development environment is 

Window : Window 7 Ultimate K Service Pack 1 64bit
CPU : Inter Core i5-4590 CPU @ 3.30GHzRAM : 8.00GB
Graphic : NVIDIA GeForce GTX 650
CMake : version 3.11
Visual Studio : 2015 

I correct EIGEN3_INCLUDE_DIR, and then configure & generate in CMake.(See below screen capture).

![image](https://user-images.githubusercontent.com/48579433/54411985-6f23cf00-4734-11e9-99e4-25d5efe30f09.png)
![image](https://user-images.githubusercontent.com/48579433/54411999-7b0f9100-4734-11e9-9e3b-d0185174a0f8.png)

and then I put Open Project and build.  
there are some errors in gtest.

C2220          warning treated as error - no 'object' file generated
LNK1181 '..\vendor\googletest-release-1.8.0\googletest\Release\gtest_main.lib' cannot open input file

![image](https://user-images.githubusercontent.com/48579433/54412142-fcffba00-4734-11e9-9fac-6068ac29a750.png)

Thanks.

**Comment by gadomski** [comment]
Sorry about the delay getting back to you on this one. I've rebuilt everything on Windows and can't reproduce the issue. Some options:

1. Try checking `gtest_force_shared_crt` and see if that solves anything.
1. I just updated CPD's vendored copy of googletest to a new version, so you could try pulling **master** and seeing if that fixes things.
1. If you don't need the tests, just disable `WITH_TESTS` and hopefully you can go on your way.

**Comment by HyeonjunKimLay** [comment]
Thanks gadomski.
I've solved this problem using the first method. I am really appreciate to you.
I can’t find to close this Issues. Is this your authority?
