### ISSUE TITLE
./cpd-rigid never terminates

### ISSUE THREAD

**Issue by AkmaralMoldagalieva** [gadomski/cpd#142]
Hello!

Thank you for this great job and for making it available to everyone!

I would like to use CPD for pose estimation. When I run ./cpd-rigid with two .csv files (each has around 9K points), it never terminates. What may cause such a problem?

Thank you!

**Comment by gadomski** [comment]
A couple of things to check:
- Make sure you're building cpd in release mode -- debug mode will slow things down a lot.
- Try making your own cpd executable that utilizes the [newly added callback mechanism](https://github.com/gadomski/cpd/commit/94094c17eb319da6f44f2742497629814303c120) to notify each iteration.
- Try with a much smaller file and then incrementally increase the file size.

Good luck, let me know how it goes!

**Comment by AkmaralMoldagalieva** [comment]
Great! Thank you. I followed your advice and checked with 3K point, and it returned some results. 
I will increase the file size and check again.
Thank you again.

**Comment by AkmaralMoldagalieva** [comment]
I am curious why did you suggest me to incrementally increase the file size?

I also would like to ask about the point sizes. Is it important that each of 2 point clouds has the same number of points (while aligning them)?

**Comment by gadomski** [comment]
> I am curious why did you suggest me to incrementally increase the file size?

Just to get a sense if things are working correctly on your machine. Rigid cpd with 10k points should take a while (a couple of minutes or more).

> Is it important that each of 2 point clouds has the same number of points (while aligning them)?

Nope, they don't have to be the same.

**Comment by AkmaralMoldagalieva** [comment]
thank you!
