### ISSUE TITLE
Install cpd with jsoncpp

### ISSUE THREAD

**Issue by markuswnuk91** [gadomski/cpd#144]
Hi, I just tried to install cpd from source with build option: JSONCPP_WITH_CMAKE_PACKAGE=ON by configruing cmake with -DJSONCPP_WITH_CMAKE_PACKAGE=ON but it failed.

Having a look at the top-level CMakeLists.txt I figured the command has changed to -DWITH_JSONCPP=ON. At least with this command the installation worked for me.

Not sure if I screwed up, but in case the command changed an update of the README.txt would help.

Thank you very much, and also thanks for the awesome library!

**Comment by gadomski** [comment]
The README's instruction to use `JSONCPP_WITH_CMAKE_PACKAGE=ON` is for a home-built jsoncpp installation -- if you don't set that option when building jsoncpp from source, there's no cmake package installed on the jsoncpp side. I'll update the readme to make that more explicit.
