### ISSUE TITLE
How to construct rigid CPD registration on windows10 by cmake

### ISSUE THREAD

**Issue by Boruson** [gadomski/cpd#151]
I try to understand the rigid registration of the CPD algorithm, but I don’t know how to construct the project. Can you give me a detailed construction? I will build on windows 10 cmake3.4.1 ?

**Comment by gadomski** [comment]
The [project README](https://github.com/gadomski/cpd/blob/master/README.md) contains basic information about building the project. This is a pretty standard CMake project, so if you're familiar with CMake you shouldn't have any big changes from what you're used to. If you're not used to building with CMake I recommend reading their tutorials/docs to get started.
