### ISSUE TITLE
cpd::Matrix 

### ISSUE THREAD

**Issue by tungtungyan** [gadomski/cpd#155]
I am using PCL to convert the matrix. It defines as a float type.  However, the cpd::Matrix defines as an Eigen::MatrixXd. Can it change to Eigen::MatrixXf? How can solve this problem?

**Comment by gadomski** [comment]
At this time, CPD's transformation functions are _not_ generic over the numeric type in the matrix. I've opened https://github.com/gadomski/cpd/issues/156 to capture the feature request.
