### ISSUE TITLE
I can't use fgt to accelerate rigid

### ISSUE THREAD

**Issue by hongyiWeng** [gadomski/cpd#158]
I have already donwload fgt from GitHub, and used "cmake" to install it.But when I make example to get fgt,I find that cpd-fgt can't be made.In order to resovle this problem,I add "find_package(Fgt REQUIRED)" in CmakeLists.txt.But when I run make again,the new problem is "‘vtable for cpd::GaussTransformFgt’undeclared".I don't have way to resolve it .If u know how to fix it,please tell me.Thank you.

**Comment by gadomski** [comment]
I was just able to configure/compile/build FGT and CPD locally, so I cannot reproduce. Make sure you are following these steps if you're building from source:
1. Clone https://github.com/gadomski/fgt
2. Configure/build/install
3. Clone https://github.com/gadomski/cpd
4. Configure/build/install, ensuring that `WITH_FGT` is `ON` in the CMakeCache and that `Fgt_DIR` is a sensible location.

**Comment by hongyiWeng** [comment]
> I was just able to configure/compile/build FGT and CPD locally, so I cannot reproduce. Make sure you are following these steps if you're building from source:
> 
> 1. Clone https://github.com/gadomski/fgt
> 2. Configure/build/install
> 3. Clone https://github.com/gadomski/cpd
> 4. Configure/build/install, ensuring that `WITH_FGT` is `ON` in the CMakeCache and that `Fgt_DIR` is a sensible location.

Thanks.I will try again!hope to be successful！
