### ISSUE TITLE
target link problem for libcpd.so

### ISSUE THREAD

**Issue by cxdcxd** [gadomski/cpd#36]
hi ,
I have a strange problems , i followed the build instructions and i can run cpd executable succesfully , but when i want to use it in my own code i have some problems. I want to use it with ROS
it is installed to (/usr/local/lib succesfully ... )

find_package(CPD required) => cant find the CPD & CPD_Directories

if I set the .so lib (libcpd.so) in target_link_libraries it's OK ,
but I have just got the undefined reference for

error: undefined reference to `cpd::NonrigidLowrank::NonrigidLowrank(float, int, float, bool, float, float, float, unsigned int)'

so , I cant compile and use CPD in my ROS package . Any Suggestion ?!

**Comment by gadomski** [comment]
Hm, before we get into manually setting `target_link_libraries`, let's figure out why your `find_package` is failing. Do you have CPD's CMake configuration scripts in `/usr/local/lib/cpd/cmake`? There should be a `CpdConfig.cmake`, `CpdTargets.cmake`, and others. Also, what's you're CMake version?

**Comment by cxdcxd** [comment]
Dear pete ,
main problem was the package name
So it should be Cpd insted  of CPD .

Solved now , but i add the libcpd.so to target link  then ...

Thanks for your reply
Edwin.

**Comment by gadomski** [comment]
No problem, glad it worked out.
