### ISSUE TITLE
Make logging better

### ISSUE THREAD

**Issue by gadomski** [gadomski/cpd#73]
Right now we just pump everything to stdout. We should be able to control logging at runtime.

**Comment by vipulraikar** [comment]
What are your thoughts on this project https://github.com/gabime/spdlog. Its header only and seems to have good performance. I will try to see how I can use this.

**Comment by gadomski** [comment]
Yeah, it's not bad. I've played with it before, and would be open to examining a pull request that added it to the library. Thanks for your interest.
