### ISSUE TITLE
Unable to obtain the correspondence Vector

### ISSUE THREAD

**Issue by hahaplus** [gadomski/cpd#75]
Hi Pete,

First of all thank you for your wonderful effort.I have tried to use your code in order to obtain the the correspondence of  two point sets,I want to get the Matching relation vector. Is the API exist？

Thanks.

**Comment by gadomski** [comment]
At this point, the rigid and non-rigid results do not produce the correspondence vector. This is something we can add, though — not sure on the timeframe, but it won't be too hard.
